from pathlib import Path

DEFAULT_SAMPLE_RATE = 16000
DEFAULT_CHANNELS = 1
DEFAULT_SAMPLE_WIDTH_BYTES = 2
DEFAULT_CONVERSATION_GAP_MS = 4000
DEFAULT_MAX_WINDOW_MS = 30000
DEFAULT_MIN_LABEL_CONFIDENCE = 0.82
DEFAULT_REVIEW_CONFIDENCE = 0.55
DEFAULT_MAX_REVIEW_ITEMS = 500
DEFAULT_MODEL_WHISPER = "whisper-large-v3"
DEFAULT_MODEL_QWEN = "qwen3.5-9b"

STATUS_SAVED = "saved"
STATUS_REVIEW = "review_required"
STATUS_DISCARDED = "discarded"
STATUS_FAILED = "failed"

SUBSYSTEM_NAME = "audio-training"
ROOT_ENV_VAR = "AUDIO_TRAINING_ROOT"


def default_root() -> Path:
    return Path(__file__).resolve().parent.parent
